import type { PageProps } from './types';
import { PageHeader } from '@/components/layout/PageHeader';
import { Card } from '@/components/ui/Card';
import { InsightCard } from '@/components/InsightCard';
import { dashboardInsights } from '@/data';
import { Sparkles, Info } from 'lucide-react';

export function AIInsightDetailPage({ navigate }: PageProps) {
  return (
    <div className="space-y-6 animate-fade-in">
      <PageHeader
        title="AI Insights"
        subtitle="Deep-dive into AI-generated business insights and their supporting evidence."
        breadcrumbs={[{ label: 'Intelligence' }, { label: 'AI Insights' }]}
      />

      <Card padding="lg">
        <div className="flex items-start gap-3">
          <div className="w-8 h-8 rounded-lg bg-brand-50 flex items-center justify-center flex-shrink-0">
            <Info className="w-4 h-4 text-brand-600" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-ink-900 mb-1">How AI Insights work</h3>
            <p className="text-sm text-ink-500 leading-relaxed">
              Insights are generated by analyzing your business data patterns across revenue, inventory, customer behavior, and promotions. Each insight includes supporting evidence from your data and leads to a specific recommended action. Insights update daily as new data flows into the system.
            </p>
          </div>
        </div>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {dashboardInsights.map((insight) => (
          <InsightCard
            key={insight.id}
            insight={insight}
            onView={() => insight.relatedProduct && navigate('product-detail', { productId: insight.relatedProduct })}
            onAction={() => navigate('ai-recommendations')}
          />
        ))}
      </div>
    </div>
  );
}
